name: fulltechsales
description: "Fulltech CRM - Seguimiento de clientes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # DATABASE LOCAL
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2

  # API / INTEGRACIÃ“N NUBE
  http: ^1.2.1
  mime: ^1.0.4
  http_parser: ^4.0.2

  # FILE PICKING
  file_picker: ^8.0.0+1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
